import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { colors, radius, space, type } from '../lib/theme';
import type { LegalDocument } from '../types/legal';

type Props = { reduceEffects: boolean; onReduceEffects: (value: boolean) => void; onShowQueue: () => void; onShowOnboarding: () => void; onOpenLegal: (document: LegalDocument) => void };
export function SettingsScreen({ reduceEffects, onReduceEffects, onShowQueue, onShowOnboarding, onOpenLegal }: Props) { return <ScrollView contentContainerStyle={styles.screen}><Text style={styles.title}>Settings</Text><Text style={styles.subtitle}>Simple defaults, always adjustable.</Text><Section title="Listening"><Row label="Default speed" value="1× Natural" /><Row label="Voice" value="Automatic" /><Row label="Pitch" value="Natural" /><Pressable style={styles.row} onPress={onShowQueue}><Text style={styles.label}>Listening queue</Text><Text style={styles.value}>Open ›</Text></Pressable></Section><Section title="Appearance"><View style={styles.row}><View><Text style={styles.label}>Reduce visual effects</Text><Text style={styles.help}>Use simpler surfaces and motion</Text></View><Switch value={reduceEffects} onValueChange={onReduceEffects} trackColor={{ false: '#D9D8DE', true: colors.accentSecondary }} /></View></Section><Section title="Privacy"><Text style={styles.privacy}>Speech uses voices on your iPhone. Saved text and listening progress stay in Soundoc. Article links are requested directly from their original website.</Text></Section><Section title="Legal"><Pressable style={styles.row} onPress={() => onOpenLegal('privacy')} accessibilityRole="link"><Text style={styles.label}>Privacy Policy</Text><Text style={styles.value}>›</Text></Pressable><Pressable style={styles.row} onPress={() => onOpenLegal('terms')} accessibilityRole="link"><Text style={styles.label}>Terms of Service</Text><Text style={styles.value}>›</Text></Pressable></Section><Section title="About"><Pressable style={styles.row} onPress={onShowOnboarding}><Text style={styles.label}>View welcome again</Text><Text style={styles.value}>›</Text></Pressable><Row label="Soundoc" value="Version 1.0" /><Row label="Storage" value="Managed locally" /></Section></ScrollView>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text><View style={styles.card}>{children}</View></View>; }
function Row({ label, value }: { label: string; value: string }) { return <View style={styles.row}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ screen: { padding: space.xl, paddingBottom: 130 }, title: { ...type.display, color: colors.textPrimary, fontSize: 30 }, subtitle: { ...type.body, color: colors.textSecondary, marginTop: space.xs }, section: { marginTop: space.xxl }, sectionTitle: { ...type.caption, color: colors.textTertiary, letterSpacing: 0.7, textTransform: 'uppercase', marginBottom: space.xs }, card: { backgroundColor: colors.surfacePrimary, borderRadius: radius.medium, borderWidth: 1, borderColor: colors.borderSubtle, overflow: 'hidden' }, row: { minHeight: 56, paddingHorizontal: space.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.divider }, label: { ...type.label, color: colors.textPrimary }, value: { ...type.label, color: colors.textSecondary }, help: { ...type.caption, color: colors.textSecondary, marginTop: 2 }, privacy: { ...type.label, color: colors.textSecondary, lineHeight: 21, padding: space.md } });
