import { useCallback, useEffect, useRef, useState } from 'react';
import { Animated, Easing, Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, radius, space, type } from '../lib/theme';

type GuideKind = 'import' | 'player' | 'studio' | 'library' | 'bookmarks' | 'privacy';

const slides: ReadonlyArray<{ kind: GuideKind; kicker: string; title: string; body: string; tips: readonly string[] }> = [
  { kind: 'import', kicker: '01 · START HERE', title: 'Bring anything to life', body: 'From Home, choose what you want to hear. Soundoc cleans it up and makes it ready to listen.', tips: ['Paste notes or copied text', 'Add a public article link', 'Upload a document or scan a photo'] },
  { kind: 'player', kicker: '02 · PLAYBACK', title: 'Your controls, at a glance', body: 'The big orange button plays and pauses. Use the side buttons to move a sentence at a time.', tips: ['Tap the progress dial to jump ahead', 'Open More for the full control panel', 'Orange glow shows the active listening action'] },
  { kind: 'studio', kicker: '03 · VOICE STUDIO', title: 'Make it sound right', body: 'Choose an iPhone voice, then tune speed, pitch, volume, and reading pauses to your taste.', tips: ['Preview a voice before choosing it', 'Listening modes set a complete sound profile', 'Your choices are saved for next time'] },
  { kind: 'library', kicker: '04 · LIBRARY & QUEUE', title: 'Keep your flow moving', body: 'Everything you add stays in your Library. Send any item to the queue for an uninterrupted listening session.', tips: ['Use Play next for the very next slot', 'Save for later to add it to the queue', 'Open the mini player from any tab'] },
  { kind: 'bookmarks', kicker: '05 · REMEMBER', title: 'Come back to the good parts', body: 'Save a bookmark or highlight while listening, then jump back to a sentence, section, or note whenever you need it.', tips: ['Bookmark the current sentence', 'Use headings to jump between sections', 'Create a private summary for a quick review'] },
  { kind: 'privacy', kicker: '06 · YOUR SPACE', title: 'Built around your attention', body: 'Your text and progress stay in Soundoc, with voices already on your iPhone. You can revisit this guide from Settings anytime.', tips: ['Use Reduce effects for a calmer interface', 'Private listening needs no account or credits', 'You are ready to start listening'] },
];

export function OnboardingModal({ onDone }: { onDone: () => void }) {
  const [page, setPage] = useState(0);
  const enter = useRef(new Animated.Value(1)).current;
  const pulse = useRef(new Animated.Value(0)).current;
  const slide = slides[page];

  useEffect(() => {
    enter.setValue(0);
    Animated.parallel([
      Animated.timing(enter, { toValue: 1, duration: 360, easing: Easing.out(Easing.cubic), useNativeDriver: true }),
    ]).start();
  }, [enter, page]);

  useEffect(() => {
    const animation = Animated.loop(Animated.sequence([
      Animated.timing(pulse, { toValue: 1, duration: 1200, easing: Easing.inOut(Easing.quad), useNativeDriver: true }),
      Animated.timing(pulse, { toValue: 0, duration: 1200, easing: Easing.inOut(Easing.quad), useNativeDriver: true }),
    ]));
    animation.start();
    return () => animation.stop();
  }, [pulse]);

  const goBack = useCallback(() => setPage((current) => Math.max(0, current - 1)), []);
  const goForward = useCallback(() => { if (page === slides.length - 1) onDone(); else setPage((current) => current + 1); }, [onDone, page]);
  const translateY = enter.interpolate({ inputRange: [0, 1], outputRange: [20, 0] });
  const previewScale = pulse.interpolate({ inputRange: [0, 1], outputRange: [0.985, 1.015] });

  return <Modal visible animationType="fade" onRequestClose={onDone} statusBarTranslucent><SafeAreaView style={styles.screen}>
    <View style={styles.ambientGlow} />
    <View style={styles.top}><View><Text style={styles.brand}>Soundoc</Text><Text style={styles.brandCaption}>YOUR LISTENING GUIDE</Text></View><Pressable onPress={onDone} accessibilityRole="button" accessibilityLabel="Skip onboarding"><Text style={styles.skip}>Skip</Text></Pressable></View>
    <Animated.View style={[styles.content, { opacity: enter, transform: [{ translateY }] }]}>
      <Animated.View style={[styles.previewFrame, { transform: [{ scale: previewScale }] }]}><FeaturePreview kind={slide.kind} pulse={pulse} /></Animated.View>
      <Text style={styles.kicker}>{slide.kicker}</Text>
      <Text style={styles.title}>{slide.title}</Text>
      <Text style={styles.body}>{slide.body}</Text>
      <View style={styles.tipCard}>{slide.tips.map((tip, index) => <View key={tip} style={styles.tipRow}><View style={styles.tipNumber}><Text style={styles.tipNumberText}>{index + 1}</Text></View><Text style={styles.tipText}>{tip}</Text></View>)}</View>
    </Animated.View>
    <View style={styles.bottom}><View style={styles.progressRow}><Text style={styles.progressText}>{page + 1} of {slides.length}</Text><View style={styles.dots}>{slides.map((entry, index) => <View key={entry.kind} style={[styles.dot, index === page && styles.activeDot]} />)}</View></View><View style={styles.actions}>{page > 0 ? <Pressable style={({ pressed }) => [styles.backButton, pressed && styles.pressed]} onPress={goBack} accessibilityRole="button" accessibilityLabel="Previous onboarding step"><Text style={styles.backArrow}>‹</Text><Text style={styles.backText}>Back</Text></Pressable> : <View style={styles.backSpacer} />}<Pressable style={({ pressed }) => [styles.button, pressed && styles.buttonPressed]} onPress={goForward} accessibilityRole="button" accessibilityLabel={page === slides.length - 1 ? 'Start listening' : 'Next onboarding step'}><Text style={styles.buttonText}>{page === slides.length - 1 ? 'Start listening' : 'Continue'}</Text><View style={styles.arrowWell}><Text style={styles.arrow}>›</Text></View></Pressable></View></View>
  </SafeAreaView></Modal>;
}

function FeaturePreview({ kind, pulse }: { kind: GuideKind; pulse: Animated.Value }) {
  const glow = pulse.interpolate({ inputRange: [0, 1], outputRange: [0.14, 0.4] });
  if (kind === 'import') return <View style={styles.previewBody}><View style={styles.previewHeader}><Text style={styles.previewBrand}>Soundoc</Text><Text style={styles.previewTiny}>NEW LISTEN</Text></View><View style={styles.sourceGrid}>{[['▤', 'Paste text'], ['↗', 'Add a link'], ['⌁', 'Scan or upload']].map(([icon, label]) => <View key={label} style={styles.sourceTile}><Text style={styles.sourceIcon}>{icon}</Text><Text style={styles.sourceLabel}>{label}</Text></View>)}</View><View style={styles.previewHomeLine}><Text style={styles.previewMuted}>Choose a source to begin</Text><Text style={styles.previewAccent}>+</Text></View></View>;
  if (kind === 'player') return <View style={styles.previewBody}><View style={styles.previewHeader}><Text style={styles.previewTiny}>NOW PLAYING</Text><Text style={styles.previewMuted}>7% complete</Text></View><View style={styles.previewPassage}><Text style={styles.previewPassageLine}>The current sentence stays in focus</Text><Text style={styles.previewPassageMuted}>and follows your listening progress.</Text></View><View style={styles.previewProgress}><Animated.View style={[styles.previewProgressActive, { opacity: glow }]} /></View><View style={styles.playerControls}><Text style={styles.skipGlyph}>‹‹</Text><Animated.View style={[styles.previewPlay, { shadowOpacity: glow }]}><Text style={styles.previewPlayGlyph}>▶</Text></Animated.View><Text style={styles.skipGlyph}>››</Text></View><View style={styles.previewChips}><Text style={styles.previewChip}>Automatic</Text><Text style={styles.previewChip}>1×</Text><Text style={styles.previewChip}>More</Text></View></View>;
  if (kind === 'studio') return <View style={styles.previewBody}><Text style={styles.previewTiny}>VOICE STUDIO</Text><View style={styles.studioVoice}><View style={styles.studioAvatar}><Text style={styles.studioAvatarText}>⌁</Text></View><View><Text style={styles.studioName}>Automatic</Text><Text style={styles.previewMuted}>Your iPhone voice</Text></View><Text style={styles.previewAccent}>›</Text></View><View style={styles.knobRow}>{[['SPEED', '1×'], ['PITCH', 'Natural'], ['VOLUME', '100%']].map(([label, value]) => <View key={label} style={styles.knob}><View style={styles.knobDial}><View style={styles.knobNotch} /></View><Text style={styles.knobLabel}>{label}</Text><Text style={styles.knobValue}>{value}</Text></View>)}</View><View style={styles.modePreview}><Text style={styles.modePreviewIcon}>✦</Text><View><Text style={styles.modePreviewTitle}>Smart mode</Text><Text style={styles.previewMuted}>Matches the material</Text></View></View></View>;
  if (kind === 'library') return <View style={styles.previewBody}><View style={styles.previewHeader}><Text style={styles.previewBrand}>Library</Text><Text style={styles.previewAccent}>Queue</Text></View>{['Daily research notes', 'Design systems article', 'Study guide'].map((title, index) => <View key={title} style={styles.libraryRow}><View style={[styles.libraryIndex, index === 0 && styles.libraryIndexActive]}><Text style={styles.libraryIndexText}>{index + 1}</Text></View><View style={styles.libraryCopy}><Text style={styles.libraryTitle}>{title}</Text><Text style={styles.previewMuted}>{index === 0 ? 'Up next · 12 min' : 'Saved for later'}</Text></View><Text style={styles.previewMuted}>⋯</Text></View>)}<View style={styles.miniPlayer}><View style={styles.miniPulse} /><View style={styles.libraryCopy}><Text style={styles.miniTitle}>Now playing</Text><Text style={styles.previewMuted}>Open from any tab</Text></View><Text style={styles.previewAccent}>Ⅱ</Text></View></View>;
  if (kind === 'bookmarks') return <View style={styles.previewBody}><View style={styles.previewHeader}><Text style={styles.previewBrand}>Bookmarks</Text><Text style={styles.previewAccent}>+ Note</Text></View><View style={styles.sectionPreview}><Text style={styles.sectionKicker}>CHAPTER 03</Text><Text style={styles.sectionTitle}>The core idea</Text><Text style={styles.previewMuted}>Tap any heading to jump there.</Text></View><View style={styles.bookmarkPreview}><View style={styles.bookmarkPin}><Text style={styles.bookmarkPinText}>⌖</Text></View><View style={styles.libraryCopy}><Text style={styles.libraryTitle}>“This is worth returning to.”</Text><Text style={styles.previewMuted}>Saved at 07:14 · Tap to jump</Text></View></View><View style={styles.summaryPreview}><Text style={styles.summaryPreviewIcon}>✦</Text><View><Text style={styles.modePreviewTitle}>Private summary</Text><Text style={styles.previewMuted}>Review key ideas quickly</Text></View></View></View>;
  return <View style={styles.previewBody}><View style={styles.lockShell}><Animated.View style={[styles.lockGlow, { opacity: glow }]} /><Text style={styles.lockIcon}>⌁</Text></View><Text style={styles.privacyTitle}>Your listening stays personal.</Text><Text style={styles.privacyBody}>Text, progress, and preferences remain in Soundoc.</Text><View style={styles.privacyPills}><Text style={styles.privacyPill}>ON YOUR IPHONE</Text><Text style={styles.privacyPill}>NO ACCOUNT</Text></View></View>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, overflow: 'hidden', backgroundColor: colors.backgroundPrimary, paddingHorizontal: space.xl, paddingTop: space.md, paddingBottom: space.xxl, justifyContent: 'space-between' },
  ambientGlow: { position: 'absolute', width: 340, height: 240, borderRadius: radius.pill, backgroundColor: colors.accentPrimary, opacity: 0.05, alignSelf: 'center', top: 76, transform: [{ scaleX: 1.18 }] },
  top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', zIndex: 1 }, brand: { ...type.title, color: colors.textPrimary, letterSpacing: -0.8 }, brandCaption: { ...type.caption, color: colors.textTertiary, letterSpacing: 1.1, marginTop: 1 }, skip: { ...type.label, color: colors.textSecondary, paddingHorizontal: space.xs, paddingVertical: space.sm },
  content: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingTop: space.sm },
  previewFrame: { width: '100%', minHeight: 248, borderRadius: radius.xlarge, padding: 1, backgroundColor: 'rgba(255,255,255,0.06)', shadowColor: '#000', shadowOpacity: 0.4, shadowOffset: { width: 0, height: 16 }, shadowRadius: 24, elevation: 10 },
  previewBody: { minHeight: 246, borderRadius: radius.xlarge, padding: space.lg, overflow: 'hidden', backgroundColor: colors.surfacePrimary, borderWidth: 1, borderTopColor: 'rgba(255,255,255,0.08)', borderBottomColor: 'rgba(0,0,0,0.66)', justifyContent: 'center' },
  previewHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, previewBrand: { ...type.title, color: colors.textPrimary, fontSize: 19 }, previewTiny: { ...type.caption, color: colors.textTertiary, letterSpacing: 0.9 }, previewMuted: { ...type.caption, color: colors.textSecondary }, previewAccent: { ...type.label, color: colors.accentPrimary },
  sourceGrid: { flexDirection: 'row', gap: 8, marginTop: space.lg }, sourceTile: { flex: 1, minHeight: 104, padding: space.sm, borderRadius: radius.medium, backgroundColor: colors.surfaceInset, borderWidth: 1, borderTopColor: 'rgba(0,0,0,0.55)', borderBottomColor: 'rgba(255,255,255,0.06)', justifyContent: 'space-between' }, sourceIcon: { color: colors.accentPrimary, fontSize: 25 }, sourceLabel: { ...type.caption, color: colors.textPrimary, lineHeight: 15 }, previewHomeLine: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: space.md, paddingHorizontal: space.sm, paddingVertical: space.xs, borderRadius: radius.small, backgroundColor: colors.accentSoft },
  previewPassage: { marginTop: space.lg, padding: space.md, borderRadius: radius.medium, backgroundColor: colors.surfaceInset }, previewPassageLine: { ...type.label, color: colors.textPrimary }, previewPassageMuted: { ...type.caption, color: colors.textTertiary, marginTop: 5 }, previewProgress: { height: 8, marginTop: space.lg, borderRadius: radius.pill, overflow: 'hidden', backgroundColor: colors.remainingProgress }, previewProgressActive: { width: '58%', height: '100%', borderRadius: radius.pill, backgroundColor: colors.accentPrimary }, playerControls: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: space.xl, marginTop: space.lg }, skipGlyph: { color: colors.textSecondary, fontSize: 20, letterSpacing: -3 }, previewPlay: { width: 58, height: 58, borderRadius: radius.pill, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.accentPrimary, shadowColor: colors.accentPrimary, shadowOffset: { width: 0, height: 7 }, shadowRadius: 12, elevation: 6 }, previewPlayGlyph: { color: '#fff', fontSize: 21, paddingLeft: 3 }, previewChips: { flexDirection: 'row', justifyContent: 'center', gap: 7, marginTop: space.md }, previewChip: { ...type.caption, color: colors.textSecondary, paddingHorizontal: space.sm, paddingVertical: 6, borderRadius: radius.small, backgroundColor: colors.surfaceInset },
  studioVoice: { flexDirection: 'row', alignItems: 'center', gap: space.sm, marginTop: space.lg, padding: space.sm, borderRadius: radius.medium, backgroundColor: colors.surfaceInset }, studioAvatar: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderRadius: radius.small, backgroundColor: colors.accentSoft }, studioAvatarText: { color: colors.accentPrimary, fontSize: 22 }, studioName: { ...type.heading, color: colors.textPrimary }, knobRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: space.lg }, knob: { alignItems: 'center', width: 76 }, knobDial: { width: 48, height: 48, alignItems: 'center', justifyContent: 'flex-start', paddingTop: 5, borderRadius: radius.pill, backgroundColor: colors.surfaceInset, borderWidth: 1, borderTopColor: 'rgba(255,255,255,0.1)', borderBottomColor: 'rgba(0,0,0,0.65)' }, knobNotch: { width: 3, height: 12, borderRadius: radius.pill, backgroundColor: colors.accentPrimary }, knobLabel: { ...type.caption, color: colors.textTertiary, fontSize: 9, marginTop: 5 }, knobValue: { ...type.caption, color: colors.textPrimary, marginTop: 1 }, modePreview: { flexDirection: 'row', alignItems: 'center', gap: space.sm, marginTop: space.md, padding: space.sm, borderRadius: radius.small, backgroundColor: colors.accentSoft }, modePreviewIcon: { color: colors.accentPrimary, fontSize: 20 }, modePreviewTitle: { ...type.label, color: colors.textPrimary },
  libraryRow: { flexDirection: 'row', alignItems: 'center', gap: space.sm, minHeight: 47, borderBottomWidth: 1, borderBottomColor: colors.divider }, libraryIndex: { width: 24, height: 24, borderRadius: radius.pill, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surfaceInset }, libraryIndexActive: { backgroundColor: colors.accentPrimary }, libraryIndexText: { ...type.caption, color: colors.textSecondary }, libraryCopy: { flex: 1, minWidth: 0 }, libraryTitle: { ...type.label, color: colors.textPrimary }, miniPlayer: { flexDirection: 'row', alignItems: 'center', gap: space.sm, marginTop: space.sm, padding: space.sm, borderRadius: radius.medium, backgroundColor: colors.accentSoft }, miniPulse: { width: 32, height: 32, borderRadius: radius.small, backgroundColor: colors.accentPrimary }, miniTitle: { ...type.label, color: colors.textPrimary },
  sectionPreview: { marginTop: space.lg, padding: space.md, borderRadius: radius.medium, backgroundColor: colors.surfaceInset }, sectionKicker: { ...type.caption, color: colors.accentPrimary, letterSpacing: 0.8 }, sectionTitle: { ...type.heading, color: colors.textPrimary, marginTop: 3 }, bookmarkPreview: { flexDirection: 'row', alignItems: 'center', gap: space.sm, marginTop: space.sm, padding: space.sm, borderRadius: radius.medium, backgroundColor: colors.surfaceInset }, bookmarkPin: { width: 36, height: 36, borderRadius: radius.small, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.accentSoft }, bookmarkPinText: { color: colors.accentPrimary, fontSize: 20 }, summaryPreview: { flexDirection: 'row', alignItems: 'center', gap: space.sm, marginTop: space.sm, padding: space.sm, borderRadius: radius.small, backgroundColor: colors.accentSoft }, summaryPreviewIcon: { color: colors.accentPrimary, fontSize: 18 },
  lockShell: { width: 96, height: 96, alignSelf: 'center', alignItems: 'center', justifyContent: 'center', borderRadius: radius.xlarge, backgroundColor: colors.surfaceInset, borderWidth: 1, borderTopColor: 'rgba(255,255,255,0.1)', borderBottomColor: 'rgba(0,0,0,0.68)' }, lockGlow: { position: 'absolute', width: 78, height: 78, borderRadius: radius.pill, backgroundColor: colors.accentPrimary }, lockIcon: { color: '#fff', fontSize: 44 }, privacyTitle: { ...type.heading, color: colors.textPrimary, textAlign: 'center', marginTop: space.lg }, privacyBody: { ...type.caption, color: colors.textSecondary, textAlign: 'center', marginTop: 5, lineHeight: 18 }, privacyPills: { flexDirection: 'row', justifyContent: 'center', gap: 7, marginTop: space.lg }, privacyPill: { ...type.caption, color: colors.accentPrimary, letterSpacing: 0.5, paddingHorizontal: space.sm, paddingVertical: 6, borderRadius: radius.small, backgroundColor: colors.accentSoft },
  kicker: { ...type.caption, color: colors.accentPrimary, letterSpacing: 1.1, marginTop: space.xxl, textAlign: 'center' }, title: { ...type.display, color: colors.textPrimary, textAlign: 'center', fontSize: 31, lineHeight: 36, marginTop: space.xs, letterSpacing: -0.7 }, body: { ...type.body, color: colors.textSecondary, textAlign: 'center', marginTop: space.sm, maxWidth: 340 }, tipCard: { alignSelf: 'stretch', gap: 8, marginTop: space.lg, padding: space.md, borderRadius: radius.large, backgroundColor: colors.surfaceInset, borderWidth: 1, borderTopColor: 'rgba(0,0,0,0.5)', borderBottomColor: 'rgba(255,255,255,0.05)' }, tipRow: { flexDirection: 'row', alignItems: 'center', gap: space.sm }, tipNumber: { width: 20, height: 20, alignItems: 'center', justifyContent: 'center', borderRadius: radius.pill, backgroundColor: colors.accentSoft }, tipNumberText: { ...type.caption, color: colors.accentPrimary, fontSize: 10 }, tipText: { ...type.caption, color: colors.textSecondary, flex: 1, lineHeight: 17 },
  bottom: { marginTop: space.sm, marginBottom: space.xs }, progressRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: space.sm }, progressText: { ...type.caption, color: colors.textTertiary }, dots: { flexDirection: 'row', gap: 5 }, dot: { width: 6, height: 6, borderRadius: radius.pill, backgroundColor: colors.borderSubtle }, activeDot: { width: 19, backgroundColor: colors.accentPrimary }, actions: { position: 'relative', minHeight: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'center' }, backButton: { position: 'absolute', left: 0, minWidth: 78, height: 48, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 4, borderRadius: radius.medium, backgroundColor: colors.surfaceInset, borderWidth: 1, borderTopColor: 'rgba(255,255,255,0.07)', borderBottomColor: 'rgba(0,0,0,0.56)' }, backSpacer: { width: 0 }, backArrow: { color: colors.textSecondary, fontSize: 23 }, backText: { ...type.label, color: colors.textSecondary }, button: { height: 50, minWidth: 190, borderRadius: radius.medium, backgroundColor: colors.accentPrimary, alignItems: 'center', justifyContent: 'space-between', paddingLeft: space.lg, paddingRight: 8, flexDirection: 'row', shadowColor: colors.accentPrimary, shadowOpacity: 0.28, shadowOffset: { width: 0, height: 8 }, shadowRadius: 14, elevation: 5 }, buttonText: { ...type.heading, color: '#FFFFFF', fontSize: 15 }, arrowWell: { width: 35, height: 35, borderRadius: radius.small, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.16)' }, arrow: { color: '#FFFFFF', fontSize: 25, lineHeight: 27 }, pressed: { opacity: 0.84, transform: [{ scale: 0.985 }] }, buttonPressed: { opacity: 0.9, transform: [{ scale: 0.98 }], shadowOpacity: 0.14, elevation: 2 },
});
